apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  secret_key: "CHANGE_ME_TO_LONG_RANDOM_STRING"
  database_url: "postgresql+asyncpg://auri:changeme@{{ .Release.Name }}-postgresql:5432/auri"
  redis_url: "redis://{{ .Release.Name }}-redis-master:6379/0"
  celery_broker_url: "redis://{{ .Release.Name }}-redis-master:6379/1"
  celery_result_backend: "redis://{{ .Release.Name }}-redis-master:6379/2"
